basePath: /
definitions:
  handlers.UserLogin:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server stock management server
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Of my apis
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - '*/*'
      description: Get test on base path.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of server.
      tags:
      - Root Base
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: Login to the application
      parameters:
      - description: UserLogin
        in: body
        name: userLogin
        required: true
        schema:
          $ref: '#/definitions/handlers.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Login to the application
      tags:
      - auth
  /api/v1/stock:
    get:
      consumes:
      - '*/*'
      description: Get test on base path.
      parameters:
      - default: Bearer
        description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of server.
      tags:
      - Stock
swagger: "2.0"
